name: ai_student_assistant
description: "AI-powered student assistant with timetable management, note-taking, chat, and flashcard generation."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1

  # Local Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.3.2
  
  # Network
  connectivity_plus: ^6.0.5

  # HTTP and API
  dio: ^5.6.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

  # Notifications
  flutter_local_notifications: ^17.2.3

  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.3
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.7.0
  
  # Image and File Handling
  image_picker: ^1.0.4
  firebase_storage: ^12.3.2
  
  # Form Enhancements
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    background_color: "#065F46"
    theme_color: "#10B981"
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
