#!/bin/bash
# Script to generate Firebase service account key for GitHub Actions

echo "Generating Firebase service account key..."
echo "This will create a service account for GitHub Actions deployment"

# Instructions for manual setup
echo ""
echo "=== MANUAL SETUP INSTRUCTIONS ==="
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/iam-admin/serviceaccounts?project=ai-student-assistant-76e9e"
echo ""
echo "2. Click 'CREATE SERVICE ACCOUNT'"
echo ""
echo "3. Service account details:"
echo "   - Name: github-actions-firebase"
echo "   - Description: Service account for GitHub Actions Firebase deployment"
echo ""
echo "4. Grant roles:"
echo "   - Firebase Hosting Admin"
echo "   - Cloud Build Service Account"
echo ""
echo "5. Create and download JSON key"
echo ""
echo "6. Copy the entire JSON content"
echo ""
echo "7. Go to your GitHub repository:"
echo "   https://github.com/assassinaj602/ai-student-assistant/settings/secrets/actions"
echo ""
echo "8. Click 'New repository secret'"
echo ""
echo "9. Name: FIREBASE_SERVICE_ACCOUNT_AI_STUDENT_ASSISTANT_76E9E"
echo "   Value: [Paste the entire JSON content]"
echo ""
echo "10. Your GitHub Actions will now automatically deploy to Firebase!"
echo ""
echo "=== TESTING AUTOMATIC DEPLOYMENT ==="
echo "After setting up the secret, make any change to your code and push:"
echo "git add ."
echo "git commit -m 'Test auto-deployment'"
echo "git push"
echo ""
echo "Check the Actions tab in your GitHub repository to see the deployment progress."