// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAlpfzKexwREP0Kcnci4UHE6bB8QHNHRI',
    appId: '1:99042279552:web:012c06eca39c5a2cf8a665',
    messagingSenderId: '99042279552',
    projectId: 'ai-student-assistant-76e9e',
    authDomain: 'ai-student-assistant-76e9e.firebaseapp.com',
    storageBucket: 'ai-student-assistant-76e9e.firebasestorage.app',
    measurementId: 'G-TBGXWZM37V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK2eGONtBeorrZdfYUGm0OftGMar7dgdI',
    appId: '1:99042279552:android:183a9bcc4caecaaef8a665',
    messagingSenderId: '99042279552',
    projectId: 'ai-student-assistant-76e9e',
    storageBucket: 'ai-student-assistant-76e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEGDqpFE74l51RlNT0X5f8ifAIysCYTI',
    appId: '1:99042279552:ios:5555dc4d6af08833f8a665',
    messagingSenderId: '99042279552',
    projectId: 'ai-student-assistant-76e9e',
    storageBucket: 'ai-student-assistant-76e9e.firebasestorage.app',
    iosClientId: '99042279552-91fviu66vnfet3vvnrfcp2bk2j954fu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiStudentAssistant',
  );
}
